import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import picOne from '../assets/00005.png'
import picTwo from '../assets/00022.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Choose the real human
        </h1>

        <div className={styles.grid}>



          
          <a className={styles.card}>
            <p>Person 1</p>
            <Image
              src={picOne}
              alt="Picture"
              width="350px"
              height="300px"
            />
          </a>

          <a className={styles.card}>
            <p>Person 2</p>
            <Image
              src={picTwo}
              alt="Picture"
              width="350px"
              height="300px"
            />
          </a>




        </div>
      </main>
    </div>
  )
}
