import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { points } from '../logic/points.js'
import { useEffect, useState } from 'react';
import image from '../image.jpeg'

export default function Home() {
  const [userPoints, setUserPoints] = useState(0);
  const [selected, setSelected] = useState(-1);
  const [countdown, setCountdown] = useState(10);
  const [correctText0, setCorrectText0] = useState('');
  const [incorrectText0, setIncorrectText0] = useState('');
  const [correctText1, setCorrectText1] = useState('');
  const [incorrectText1, setIncorrectText1] = useState('');
  const [iteration, setIteration] = useState(0);
  const [clickable, setClickable] = useState(true);

  function reset_animation() {
    var el = document.querySelector('svg circle');
    el.style.animationName = "none";

    requestAnimationFrame(() => {
      setTimeout(() => {
        el.style.animationName = ""
      }, 0);
    });

    el.style.animationPlayState = '';
  }

  function resetText() {
    setCorrectText0('');
    setCorrectText1('');
    setIncorrectText0('');
    setIncorrectText1('');
  }

  useEffect(() => {
    setTimeout(() => {
      if (countdown-1 == 0) {
        document.querySelector('svg circle').style.animationPlayState = 'paused';
        document.querySelector('svg circle').style.animationDelay = '0s';
      }

      if (countdown >= 1) setCountdown(countdown-1);

      if (countdown == 0) {
        result();
        setCountdown(10);
        if (iteration%2 == 0) {
          setClickable(false);
        } else {
          resetText();
          setClickable(true);
        }
        setIteration(iteration+1);
        reset_animation();
      }
    }, 1000);
  }, [countdown]);

  function percent(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
  }

  function result() {
    let correct = points(selected);
    let t = `${percent(40, 60)}% players chose this option`;
    
    if (selected >= 0) {
      if (correct) {
        (selected == 0) ? setCorrectText0(t) : setCorrectText1(t);
        setUserPoints(userPoints+10);
      } else {
        (selected == 0) ? setIncorrectText0(t) : setIncorrectText1(t);
      }
    } else {
      (correct = 0) ? setCorrectText0(t) : setCorrectText1(t);
    }
    
  }

  function selectImage(selected) {
    if (clickable) {
      setSelected(selected);
      document.querySelectorAll('.photo')[0].style.cssText = "";
      document.querySelectorAll('.photo')[1].style.cssText = "";
      document.querySelectorAll('.photo')[selected].style.cssText = "border: 5px solid white;";
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Real Human</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div id="countdown" className={styles.countdown}>
          <div id="countdownText" className={styles.countdownText}>{countdown}</div>
          <svg className={styles.svg}>
            <circle r="45" cx="50" cy="50"></circle>
          </svg>
        </div>

        <h1 className={styles.title}>
          Choose the real human
        </h1>
        
        <div className={styles.grid}>

          <div>
            <div onClick={() => selectImage(0)} className={`${styles.card} photo`}>
              <Image
                className={styles.img}
                src={image}
                alt="Picture"
                width="300px"
                height="300px"
              />
            </div>

            <h3 className={styles.correctText}>{correctText0}</h3>
            <h3 className={styles.incorrectText}>{incorrectText0}</h3>
          </div>
          
          <div>
            <div onClick={() => selectImage(1)} className={`${styles.card} photo`}>
              <Image
                className={styles.img}
                src={image}
                alt="Picture"
                width="300px"
                height="300px"
                onLoad={ () => { setCountdown(10); } }
              />
            </div>

            <h3 className={styles.correctText}>{correctText1}</h3>
            <h3 className={styles.incorrectText}>{incorrectText1}</h3>
          </div>
    
        </div>

        <h2 id="points">Points: {userPoints}</h2>

      </main>
    </div>
  )
}
