import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import picOne from '../assets/00005.png'
import picTwo from '../assets/00022.png'
import points from '../logic/points.js'

function selectImage() {
  alert("TEST");
  // alert(JSON.stringify(points));
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Real Human</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Choose the real human
        </h1>
        
        <h2>Points: 0</h2>
        
        <div className={styles.grid}>

          <div onClick={selectImage} className={styles.card}>
              <Image
                src={picOne}
                alt="Picture"
                width="300px"
                height="300px"
              />
          </div>

          <div onClick={selectImage} className={styles.card}>
            <Image
              src={picTwo}
              alt="Picture"
              width="300px"
              height="300px"
            />
          </div>




        </div>
      </main>
    </div>
  )
}
